export enum KohaSettingKeys {
  KOHA_BASE_URL = "KOHA_BASE_URL",
  KOHA_API_KEY = "KOHA_API_KEY",
  KOHA_TIMEOUT_MS = "KOHA_TIMEOUT_MS",
  KOHA_RETRY_COUNT = "KOHA_RETRY_COUNT",
  KOHA_AUTH_TYPE = "KOHA_AUTH_TYPE",
  KOHA_USERNAME = "KOHA_USERNAME",
  KOHA_PASSWORD = "KOHA_PASSWORD",
  LIBRARY_CLEARANCE_REQUIRED = "LIBRARY_CLEARANCE_REQUIRED",
}

export enum KohaAuthType {
  AUTHORIZATION = "AUTHORIZATION",
  X_KOHA_TOKEN = "X_KOHA_TOKEN",
  BASIC_AUTH = "BASIC_AUTH",
}
