[unix_http_server]
file=/tmp/supervisor.sock

[supervisord]
logfile=outputs/logs/supervisord.log
pidfile=supervisord.pid
logfile_maxbytes=5MB
logfile_backups=5

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:attendance-service]
command=uv run uvicorn app.main:app --host 0.0.0.0 --port 8000
directory=%(here)s
autostart=true
autorestart=true
stderr_logfile=outputs/logs/attendance.err.log
stdout_logfile=outputs/logs/attendance.out.log
stopasgroup=true
